// Generates src/api/types.gen.ts from src/api/schema.json, the JSON Schema
// exported by `python -m xoot.dashboard.export_schema`. A vitest test runs
// generateTypes() too and fails when the committed output has drifted.
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

import { compile } from 'json-schema-to-typescript';
import { format, resolveConfig } from 'prettier';

export const SCHEMA_PATH = fileURLToPath(
  new URL('../src/api/schema.json', import.meta.url),
);
export const TYPES_PATH = fileURLToPath(
  new URL('../src/api/types.gen.ts', import.meta.url),
);

const BANNER =
  '// Generated by `npm run gen:types` from src/api/schema.json. Do not edit.\n';

// Pydantic titles every property; json2ts would turn each title into its own
// alias (Key, Key1, ...). Only the named definitions keep their titles.
function dropPropertyTitles(node, isDefinition) {
  if (Array.isArray(node)) {
    return node.map((child) => dropPropertyTitles(child, false));
  }
  if (node === null || typeof node !== 'object') {
    return node;
  }
  const result = {};
  for (const [name, value] of Object.entries(node)) {
    if (name === 'title' && !isDefinition) {
      continue;
    }
    // Keys of these maps are names, not keywords: a property may be "title".
    if ((name === '$defs' || name === 'properties') && isRecord(value)) {
      result[name] = Object.fromEntries(
        Object.entries(value).map(([key, child]) => [
          key,
          dropPropertyTitles(child, name === '$defs'),
        ]),
      );
      continue;
    }
    result[name] = dropPropertyTitles(value, false);
  }
  return result;
}

function isRecord(value) {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

/** @param {string} schemaText @returns {Promise<string>} */
export async function generateTypes(schemaText) {
  const schema = dropPropertyTitles(JSON.parse(schemaText), true);
  const code = await compile(schema, 'XootDashboardApi', {
    bannerComment: '',
    additionalProperties: false,
    unreachableDefinitions: true,
    format: false,
  });
  const options = await resolveConfig(TYPES_PATH);
  return format(BANNER + code, { ...options, parser: 'typescript' });
}

async function main() {
  const schemaText = await readFile(SCHEMA_PATH, 'utf-8');
  await writeFile(TYPES_PATH, await generateTypes(schemaText), 'utf-8');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await main();
}
