// Generated by `npm run gen:types` from src/api/schema.json. Do not edit.
/**
 * Claude acting through a client, the user directly, or xoot itself.
 *
 * SYSTEM is for changes xoot derives from another actor's write (a goal or
 * batch completing or reopening, workflow remaps); they keep that write's
 * client.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ActorKind".
 */
export type ActorKind = 'claude' | 'user' | 'system';
/**
 * The fixed set of categories. Project workflows name their own states,
 * but every state belongs to exactly one of these, and domain rules
 * (completion, backlog counts, tree filtering) reason only in categories.
 * Backlog is an item kind, not a category.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "Category".
 */
export type Category =
  'open' | 'active' | 'blocked' | 'awaiting_input' | 'done' | 'dropped';
/**
 * A goal holds batches, a batch holds subtasks. A backlog item is open work
 * found along the way; it sits on a batch, a goal or the project.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ItemKind".
 */
export type ItemKind = 'goal' | 'batch' | 'subtask' | 'backlog';
/**
 * Superseded is terminal and only reached by a newer decision.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "DecisionStatus".
 */
export type DecisionStatus = 'locked' | 'deferred' | 'superseded';
/**
 * Where a write came from; recorded on every event.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "Client".
 */
export type Client = 'chat' | 'code' | 'paste' | 'cli';
/**
 * The kind of mutation an event row describes.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "EventAction".
 */
export type EventAction =
  | 'create'
  | 'update'
  | 'add_alias'
  | 'add_path'
  | 'remove_alias'
  | 'remove_path'
  | 'redact';

export interface XootDashboardApi {
  [k: string]: unknown;
}
/**
 * The backlog entry plus when the item was created and why it was
 * captured: the first line of its body, cut to WHY_MAX characters.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "BacklogRow".
 */
export interface BacklogRow {
  category: Category | null;
  created_at: string;
  found_on: string | null;
  key: string;
  kind: ItemKind;
  level: 'project' | 'goal' | 'batch';
  parent: string | null;
  state: string;
  title: string;
  version: number;
  why: string;
}
/**
 * Open backlog items of every level, project level first, then by key;
 * truncated when the cap hid items.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "BacklogView".
 */
export interface BacklogView {
  items: BacklogRow[];
  project: string;
  truncated: boolean;
}
/**
 * Every child is done or dropped, but open_backlog backlog items still sit
 * on it: cover them, resolve them (item_update to done) or push them up.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "BlockedEntry".
 */
export interface BlockedEntry {
  key: string;
  open_backlog: number;
}
/**
 * The brief_get picture without its MCP-only fields: counts, open goals
 * with batch progress, work in flight, what open backlog blocks, open
 * backlog per level, recent decisions and the workflow.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "BriefView".
 */
export interface BriefView {
  active: ItemSummary[];
  awaiting_input: ItemSummary[];
  backlog_counts: {
    [k: string]: number;
  };
  blocked: BlockedEntry[];
  counts: {
    [k: string]: number;
  };
  open_goals: GoalProgressEntry[];
  open_goals_truncated: boolean;
  project: ProjectInfo;
  recent_decisions: DecisionSummary[];
  workflow: {
    [k: string]: WorkflowEntry;
  };
}
/**
 * Enough to recognize, pick and update an item. key is its nested path
 * within the project; category is the fixed meaning of the
 * project-defined state; version is what item_update needs.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ItemSummary".
 */
export interface ItemSummary {
  category: Category | null;
  key: string;
  kind: ItemKind;
  parent: string | null;
  state: string;
  title: string;
  version: number;
}
/**
 * batches_done of batches_total are done (dropped batches count in
 * neither); open_backlog counts the open backlog anywhere in the goal.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "GoalProgressEntry".
 */
export interface GoalProgressEntry {
  batches_done: number;
  batches_total: number;
  category: Category | null;
  key: string;
  open_backlog: number;
  state: string;
  title: string;
  version: number;
}
/**
 * The key prefix the URLs use, the display name and the aliases.
 * Registered paths are left out: the browser has no use for local paths.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ProjectInfo".
 */
export interface ProjectInfo {
  aliases: string[];
  key_prefix: string;
  name: string;
}
/**
 * A decision's key (<owner key>/decision-<n>), title, status, the item it
 * was made on, the decision it supersedes, and its version.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "DecisionSummary".
 */
export interface DecisionSummary {
  key: string;
  owner: string | null;
  status: DecisionStatus;
  supersedes: string | null;
  title: string;
  updated_at: string;
  version: number;
}
/**
 * Every state of one kind with its category, so a client picks real state
 * names, and whether only listed transitions are allowed.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "WorkflowEntry".
 */
export interface WorkflowEntry {
  states: StateSpec[];
  transitions_restricted: boolean;
}
/**
 * A project-chosen state name and the fixed category it belongs to.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "StateSpec".
 */
export interface StateSpec {
  category: Category;
  name: string;
}
/**
 * The project's newest event id; the dashboard polls it for changes.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ChangesView".
 */
export interface ChangesView {
  latest_event_id: number;
}
/**
 * How many children there are per category, and the first few of them.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ChildrenSummary".
 */
export interface ChildrenSummary {
  by_category: {
    [k: string]: number;
  };
  items: ItemSummary[];
  total: number;
  truncated: boolean;
}
/**
 * The summary plus the body and creation time.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "DecisionDetail".
 */
export interface DecisionDetail {
  body: string;
  created_at: string;
  key: string;
  owner: string | null;
  status: DecisionStatus;
  supersedes: string | null;
  title: string;
  updated_at: string;
  version: number;
}
/**
 * One decision with its body.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "DecisionView".
 */
export interface DecisionView {
  decision: DecisionDetail;
}
/**
 * Decisions, newest first.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "DecisionsView".
 */
export interface DecisionsView {
  decisions: DecisionSummary[];
  project: string;
  truncated: boolean;
}
/**
 * The error class name and a safe message, built by the same rules as MCP
 * tool errors: never driver text, SQL or an arbitrary input value.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ErrorOutput".
 */
export interface ErrorOutput {
  error: string;
  message: string;
}
/**
 * Who changed what and when. changed names every changed field, body
 * included; before/after hold the non-body values, with keys for references.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "EventEntry".
 */
export interface EventEntry {
  action: EventAction;
  actor_kind: ActorKind;
  after: {
    [k: string]: unknown;
  } | null;
  before: {
    [k: string]: unknown;
  } | null;
  changed: string[];
  client: Client;
  created_at: string;
  redacted: boolean;
}
/**
 * The summary plus the body, the awaited decision, the backlog links
 * (found_on and covered_by on a backlog item, origin on a subtask made
 * from one), every older key that still resolves to it, and timestamps.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ItemDetail".
 */
export interface ItemDetail {
  aliases: string[];
  awaiting_decision: string | null;
  body: string;
  category: Category | null;
  covered_by: string | null;
  created_at: string;
  found_on: string | null;
  key: string;
  kind: ItemKind;
  origin: string | null;
  parent: string | null;
  state: string;
  title: string;
  updated_at: string;
  version: number;
}
/**
 * One item in full: its children (work first, then backlog), its most
 * recent events (newest first) and the decisions made on it, with bodies.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ItemView".
 */
export interface ItemView {
  children: ChildrenSummary;
  decisions: DecisionDetail[];
  events: EventEntry[];
  item: ItemDetail;
}
/**
 * The running xoot version.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "MetaOutput".
 */
export interface MetaOutput {
  version: string;
}
/**
 * Every registered project, by key prefix.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ProjectsOutput".
 */
export interface ProjectsOutput {
  projects: ProjectInfo[];
}
/**
 * An item and its depth below the query's roots.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "TreeEntry".
 */
export interface TreeEntry {
  depth: number;
  item: ItemSummary;
}
/**
 * Tree nodes in pre-order; truncated says the bounds hid items. blocked
 * lists every goal and batch of the project that open backlog holds open,
 * uncapped, so any node can show it.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "TreeView".
 */
export interface TreeView {
  blocked: BlockedEntry[];
  nodes: TreeEntry[];
  project: string;
  truncated: boolean;
}
