// Generated by `npm run gen:types` from src/api/schema.json. Do not edit.
/**
 * Claude acting through a client, the user directly, or xoot itself.
 *
 * SYSTEM is for changes xoot derives from another actor's write (stale
 * backlog moves, workflow remaps); they keep that write's client and
 * session.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ActorKind".
 */
export type ActorKind = 'claude' | 'user' | 'system';
/**
 * The fixed set of categories. Project workflows name their own states,
 * but every state belongs to exactly one of these, and domain rules
 * (backlogs, session close, tree filtering) reason only in categories.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "Category".
 */
export type Category =
  'open' | 'active' | 'blocked' | 'awaiting_input' | 'done' | 'dropped' | 'backlogged';
/**
 * A goal holds batches, a batch holds subtasks; subtasks may be unfiled.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ItemKind".
 */
export type ItemKind = 'goal' | 'batch' | 'subtask';
/**
 * Where a write came from; recorded on sessions and on every event.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "Client".
 */
export type Client = 'chat' | 'code' | 'paste' | 'cli';
/**
 * Sessions start open and are closed exactly once.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "SessionStatus".
 */
export type SessionStatus = 'open' | 'closed';
/**
 * Superseded is terminal and only reached by a newer decision.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "DecisionStatus".
 */
export type DecisionStatus = 'locked' | 'deferred' | 'superseded';
/**
 * The kind of mutation an event row describes.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "EventAction".
 */
export type EventAction =
  | 'create'
  | 'update'
  | 'link'
  | 'dispose'
  | 'close'
  | 'add_alias'
  | 'add_path'
  | 'remove_alias'
  | 'remove_path'
  | 'redact';

export interface XootDashboardApi {
  [k: string]: unknown;
}
/**
 * Each open session's backlog, the project backlog and the unfiled
 * subtasks. A capture shows under its session and under unfiled.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "BacklogsView".
 */
export interface BacklogsView {
  project: string;
  project_backlog: ItemSummary[];
  project_backlog_truncated: boolean;
  sessions: SessionBacklogEntry[];
  unfiled: ItemSummary[];
  unfiled_truncated: boolean;
}
/**
 * Enough to recognize, pick and update an item. category is the fixed
 * meaning of the project-defined state; version is what item_update needs.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ItemSummary".
 */
export interface ItemSummary {
  backlog_session: string | null;
  category: Category | null;
  key: string;
  kind: ItemKind;
  parent: string | null;
  state: string;
  title: string;
  version: number;
}
/**
 * An open session and the items parked in its backlog.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "SessionBacklogEntry".
 */
export interface SessionBacklogEntry {
  items: ItemSummary[];
  session: SessionSummary;
  truncated: boolean;
}
/**
 * A session's key, title, client, status and timestamps.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "SessionSummary".
 */
export interface SessionSummary {
  client: Client;
  closed_at: string | null;
  key: string;
  started_at: string;
  status: SessionStatus;
  title: string;
}
/**
 * The brief_get picture without its MCP-only fields: counts, open
 * sessions, work in flight, backlogs, recent decisions and the workflow.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "BriefView".
 */
export interface BriefView {
  active: ItemSummary[];
  awaiting_input: ItemSummary[];
  counts: {
    [k: string]: number;
  };
  open_session_backlog: ItemSummary[];
  open_session_backlog_truncated: boolean;
  open_sessions: SessionSummary[];
  open_sessions_truncated: boolean;
  pending_session_backlog: ItemSummary[];
  project: ProjectInfo;
  project_backlog_count: number;
  recent_decisions: DecisionSummary[];
  workflow: {
    [k: string]: WorkflowEntry;
  };
}
/**
 * The key prefix the URLs use, the display name and the aliases.
 * Registered paths are left out: the browser has no use for local paths.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ProjectInfo".
 */
export interface ProjectInfo {
  aliases: string[];
  key_prefix: string;
  name: string;
}
/**
 * A decision's key, title, status, references and version.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "DecisionSummary".
 */
export interface DecisionSummary {
  key: string;
  scope: string | null;
  status: DecisionStatus;
  supersedes: string | null;
  title: string;
  updated_at: string;
  version: number;
}
/**
 * Every state of one kind with its category, so a client picks real state
 * names, and whether only listed transitions are allowed.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "WorkflowEntry".
 */
export interface WorkflowEntry {
  states: StateSpec[];
  transitions_restricted: boolean;
}
/**
 * A project-chosen state name and the fixed category it belongs to.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "StateSpec".
 */
export interface StateSpec {
  category: Category;
  name: string;
}
/**
 * The project's newest event id; the dashboard polls it for changes.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ChangesView".
 */
export interface ChangesView {
  latest_event_id: number;
}
/**
 * How many children there are per category, and the first few of them.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ChildrenSummary".
 */
export interface ChildrenSummary {
  by_category: {
    [k: string]: number;
  };
  items: ItemSummary[];
  total: number;
  truncated: boolean;
}
/**
 * The summary plus the body and creation time.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "DecisionDetail".
 */
export interface DecisionDetail {
  body: string;
  created_at: string;
  key: string;
  scope: string | null;
  status: DecisionStatus;
  supersedes: string | null;
  title: string;
  updated_at: string;
  version: number;
}
/**
 * One decision with its body.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "DecisionView".
 */
export interface DecisionView {
  decision: DecisionDetail;
}
/**
 * Decisions, newest first.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "DecisionsView".
 */
export interface DecisionsView {
  decisions: DecisionSummary[];
  project: string;
  truncated: boolean;
}
/**
 * The error class name and a safe message, built by the same rules as MCP
 * tool errors: never driver text, SQL or an arbitrary input value.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ErrorOutput".
 */
export interface ErrorOutput {
  error: string;
  message: string;
}
/**
 * Who changed what and when. changed names every changed field, body
 * included; before/after hold the non-body values, with keys for references.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "EventEntry".
 */
export interface EventEntry {
  action: EventAction;
  actor_kind: ActorKind;
  after: {
    [k: string]: unknown;
  } | null;
  before: {
    [k: string]: unknown;
  } | null;
  changed: string[];
  client: Client;
  created_at: string;
  redacted: boolean;
  session: string | null;
}
/**
 * The summary plus the body, the awaited decision and timestamps.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ItemDetail".
 */
export interface ItemDetail {
  awaiting_decision: string | null;
  backlog_session: string | null;
  body: string;
  category: Category | null;
  created_at: string;
  key: string;
  kind: ItemKind;
  parent: string | null;
  state: string;
  title: string;
  unfiled: boolean;
  updated_at: string;
  version: number;
}
/**
 * One item in full: its children, most recent events (newest first), the
 * sessions it is linked to and the decisions scoped to it, with bodies.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ItemView".
 */
export interface ItemView {
  children: ChildrenSummary;
  decisions: DecisionDetail[];
  events: EventEntry[];
  item: ItemDetail;
  sessions: SessionSummary[];
}
/**
 * The running xoot version.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "MetaOutput".
 */
export interface MetaOutput {
  version: string;
}
/**
 * Every registered project, by key prefix.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ProjectsOutput".
 */
export interface ProjectsOutput {
  projects: ProjectInfo[];
}
/**
 * One session, its close summary, and the keys of the items it is linked
 * to, which the tree overlay highlights.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "SessionView".
 */
export interface SessionView {
  items: string[];
  session: SessionSummary;
  summary: string | null;
}
/**
 * Sessions, open ones first, then newest first.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "SessionsView".
 */
export interface SessionsView {
  project: string;
  sessions: SessionSummary[];
  truncated: boolean;
}
/**
 * An item and its depth below the query's roots.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "TreeEntry".
 */
export interface TreeEntry {
  depth: number;
  item: ItemSummary;
  unfiled: boolean;
}
/**
 * Tree nodes in pre-order; truncated says the bounds hid items.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "TreeView".
 */
export interface TreeView {
  nodes: TreeEntry[];
  project: string;
  truncated: boolean;
}
