// Generated by `npm run gen:types` from src/api/schema.json. Do not edit.
/**
 * Claude acting through a client, the user directly, or xoot itself.
 *
 * SYSTEM is for changes xoot derives from another actor's write (a goal or
 * batch completing or reopening, workflow remaps); they keep that write's
 * client.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ActorKind".
 */
export type ActorKind = 'claude' | 'user' | 'system';
/**
 * The fixed set of categories. Project workflows name their own states,
 * but every state belongs to exactly one of these, and domain rules
 * (completion, backlog counts, tree filtering) reason only in categories.
 * Backlog is an item kind, not a category.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "Category".
 */
export type Category =
  'open' | 'active' | 'blocked' | 'awaiting_input' | 'done' | 'dropped';
/**
 * A goal holds batches, a batch holds subtasks. A backlog item is open work
 * found along the way; it sits on a batch, a goal or the project.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ItemKind".
 */
export type ItemKind = 'goal' | 'batch' | 'subtask' | 'backlog';
/**
 * Superseded is terminal and only reached by a newer decision.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "DecisionStatus".
 */
export type DecisionStatus = 'locked' | 'deferred' | 'superseded';
/**
 * Where a write came from; recorded on every event.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "Client".
 */
export type Client = 'chat' | 'code' | 'paste' | 'cli' | 'dashboard';
/**
 * Superseded is terminal and only reached by a newer decision.
 */
export type DecisionStatus1 = 'locked' | 'deferred' | 'superseded';
/**
 * The kind of mutation an event row describes.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "EventAction".
 */
export type EventAction =
  | 'create'
  | 'update'
  | 'add_alias'
  | 'add_path'
  | 'remove_alias'
  | 'remove_path'
  | 'redact';

export interface XootDashboardApi {
  [k: string]: unknown;
}
/**
 * The item's state, parent and new version, enough for the next item_update.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "AffectedItemEntry".
 */
export interface AffectedItemEntry {
  key: string;
  parent: string | null;
  state: string;
  version: number;
}
/**
 * The backlog entry plus when the item was created and why it was
 * captured: the first line of its body, cut to WHY_MAX characters.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "BacklogRow".
 */
export interface BacklogRow {
  category: Category | null;
  created_at: string;
  found_on: string | null;
  key: string;
  kind: ItemKind;
  level: 'project' | 'goal' | 'batch';
  parent: string | null;
  state: string;
  title: string;
  version: number;
  why: string;
}
/**
 * Open backlog items of every level, project level first, then by key;
 * truncated when the cap hid items.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "BacklogView".
 */
export interface BacklogView {
  items: BacklogRow[];
  project: string;
  truncated: boolean;
}
/**
 * Every child is done or dropped, but open_backlog backlog items still sit
 * on it: cover them, resolve them (item_update to done) or push them up.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "BlockedEntry".
 */
export interface BlockedEntry {
  key: string;
  open_backlog: number;
}
/**
 * The brief_get picture without its MCP-only fields: counts, open goals
 * with batch progress, work in flight, what open backlog blocks, open
 * backlog per level, recent decisions and the workflow.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "BriefView".
 */
export interface BriefView {
  active: ItemSummary[];
  awaiting_input: ItemSummary[];
  backlog_counts: {
    [k: string]: number;
  };
  blocked: BlockedEntry[];
  counts: {
    [k: string]: number;
  };
  open_goals: GoalProgressEntry[];
  open_goals_truncated: boolean;
  project: ProjectInfo;
  recent_decisions: DecisionSummary[];
  workflow: {
    [k: string]: WorkflowEntry;
  };
}
/**
 * Enough to recognize, pick and update an item. key is its nested path
 * within the project; category is the fixed meaning of the
 * project-defined state; version is what item_update needs.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ItemSummary".
 */
export interface ItemSummary {
  category: Category | null;
  key: string;
  kind: ItemKind;
  parent: string | null;
  state: string;
  title: string;
  version: number;
}
/**
 * batches_done of batches_total are done (dropped batches count in
 * neither); open_backlog counts the open backlog anywhere in the goal.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "GoalProgressEntry".
 */
export interface GoalProgressEntry {
  batches_done: number;
  batches_total: number;
  category: Category | null;
  key: string;
  open_backlog: number;
  state: string;
  title: string;
  version: number;
}
/**
 * The key prefix the URLs use, the display name and the aliases.
 * Registered paths are left out: the browser has no use for local paths.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ProjectInfo".
 */
export interface ProjectInfo {
  aliases: string[];
  key_prefix: string;
  name: string;
}
/**
 * A decision's key (<owner key>/decision-<n>), title, status, the item it
 * was made on, the decision it supersedes, and its version.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "DecisionSummary".
 */
export interface DecisionSummary {
  key: string;
  owner: string | null;
  status: DecisionStatus;
  supersedes: string | null;
  title: string;
  updated_at: string;
  version: number;
}
/**
 * Every state of one kind with its category, so a client picks real state
 * names, and whether only listed transitions are allowed.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "WorkflowEntry".
 */
export interface WorkflowEntry {
  states: StateSpec[];
  transitions_restricted: boolean;
}
/**
 * A project-chosen state name and the fixed category it belongs to.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "StateSpec".
 */
export interface StateSpec {
  category: Category;
  name: string;
}
/**
 * Open work found on an item, with a body saying why it needs doing.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "CaptureRequest".
 */
export interface CaptureRequest {
  body: string;
  found_on: string;
  title: string;
}
/**
 * The item key and its changed fields, old and new, with keys for
 * references; a move includes the number the item takes.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ChangeEntry".
 */
export interface ChangeEntry {
  after: {
    [k: string]: unknown;
  };
  before: {
    [k: string]: unknown;
  };
  key: string;
}
/**
 * The project's newest event id; the dashboard polls it for changes.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ChangesView".
 */
export interface ChangesView {
  latest_event_id: number;
}
/**
 * How many children there are per category, and the first few of them.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ChildrenSummary".
 */
export interface ChildrenSummary {
  by_category: {
    [k: string]: number;
  };
  items: ItemSummary[];
  total: number;
  truncated: boolean;
}
/**
 * The new subtask, the backlog item it closed, and the engine's outcome.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "CoverOutput".
 */
export interface CoverOutput {
  backlog: ItemSummary;
  blocked?: BlockedEntry[];
  changed?: VersionEntry[];
  completed?: string[];
  project: string;
  reopened?: string[];
  subtask: ItemDetail;
}
/**
 * The item's key, new version and state, for the next expected_version.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "VersionEntry".
 */
export interface VersionEntry {
  key: string;
  state: string;
  version: number;
}
/**
 * The summary plus the body, the awaited decision, the backlog links
 * (found_on and covered_by on a backlog item, origin on a subtask made
 * from one), every older key that still resolves to it, and timestamps.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ItemDetail".
 */
export interface ItemDetail {
  aliases: string[];
  awaiting_decision: string | null;
  body: string;
  category: Category | null;
  covered_by: string | null;
  created_at: string;
  found_on: string | null;
  key: string;
  kind: ItemKind;
  origin: string | null;
  parent: string | null;
  state: string;
  title: string;
  updated_at: string;
  version: number;
}
/**
 * Turn a backlog item into a subtask and close it. A goal-level item needs
 * the batch to cover it in; a batch-level one is covered in its own batch.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "CoverRequest".
 */
export interface CoverRequest {
  batch?: string | null;
  key: string;
}
/**
 * A decision on the goal, batch or subtask it was made on; supersedes names
 * an older decision of the same goal, which becomes superseded.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "DecisionCreateRequest".
 */
export interface DecisionCreateRequest {
  body?: string;
  owner: string;
  status?: DecisionStatus1;
  supersedes?: string | null;
  title: string;
}
/**
 * The summary plus the body and creation time.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "DecisionDetail".
 */
export interface DecisionDetail {
  body: string;
  created_at: string;
  key: string;
  owner: string | null;
  status: DecisionStatus;
  supersedes: string | null;
  title: string;
  updated_at: string;
  version: number;
}
/**
 * One decision in full, and the project it belongs to.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "DecisionOutput".
 */
export interface DecisionOutput {
  decision: DecisionDetail;
  project: string;
}
/**
 * New title, body or status of a decision, based on expected_version.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "DecisionUpdateRequest".
 */
export interface DecisionUpdateRequest {
  body?: string | null;
  expected_version: number;
  status?: DecisionStatus | null;
  title?: string | null;
}
/**
 * One decision with its body.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "DecisionView".
 */
export interface DecisionView {
  decision: DecisionDetail;
}
/**
 * Decisions, newest first.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "DecisionsView".
 */
export interface DecisionsView {
  decisions: DecisionSummary[];
  project: string;
  truncated: boolean;
}
/**
 * The error class name and a safe message, built by the same rules as MCP
 * tool errors: never driver text, SQL or an arbitrary input value.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ErrorOutput".
 */
export interface ErrorOutput {
  error: string;
  message: string;
}
/**
 * Who changed what and when. changed names every changed field, body
 * included; before/after hold the non-body values, with keys for references.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "EventEntry".
 */
export interface EventEntry {
  action: EventAction;
  actor_kind: ActorKind;
  after: {
    [k: string]: unknown;
  } | null;
  before: {
    [k: string]: unknown;
  } | null;
  changed: string[];
  client: Client;
  created_at: string;
  redacted: boolean;
}
/**
 * A new goal, batch or subtask. A goal takes no parent, a batch a goal and
 * a subtask a batch; backlog items come from capture.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ItemCreateRequest".
 */
export interface ItemCreateRequest {
  body?: string;
  kind: 'goal' | 'batch' | 'subtask';
  parent?: string | null;
  title: string;
}
/**
 * mode is the path taken. A direct update returns the item. A drop or
 * reparent of an item with children first returns a preview plan and a
 * confirm_token, then the applied plan; an applied drop or reparent also
 * returns every item it changed, as it now stands, in items. A reparent
 * re-keys the moved subtree; the old keys keep resolving.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ItemUpdateOutput".
 */
export interface ItemUpdateOutput {
  blocked?: BlockedEntry[];
  changed?: VersionEntry[];
  completed?: string[];
  confirm_token: string | null;
  item: ItemDetail | null;
  items?: AffectedItemEntry[] | null;
  mode: 'update' | 'drop' | 'reparent';
  phase: 'preview' | 'applied';
  plan: SubtreeOutput | null;
  project: string;
  reopened?: string[];
}
/**
 * Every row that changes, in write order; a move lists each key change.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "SubtreeOutput".
 */
export interface SubtreeOutput {
  changes: ChangeEntry[];
  root: string;
}
/**
 * New title, body or state, based on expected_version. Dropping an item that
 * has children first returns a preview and a confirm_token; send the state
 * alone, then the same body plus the token.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ItemUpdateRequest".
 */
export interface ItemUpdateRequest {
  body?: string | null;
  confirm_token?: string | null;
  expected_version: number;
  state?: string | null;
  title?: string | null;
}
/**
 * One item in full: its children (work first, then backlog), its most
 * recent events (newest first) and the decisions made on it, with bodies.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ItemView".
 */
export interface ItemView {
  children: ChildrenSummary;
  decisions: DecisionDetail[];
  events: EventEntry[];
  item: ItemDetail;
}
/**
 * The new item, and what the completion engine did.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ItemWriteOutput".
 */
export interface ItemWriteOutput {
  blocked?: BlockedEntry[];
  changed?: VersionEntry[];
  completed?: string[];
  item: ItemDetail;
  project: string;
  reopened?: string[];
}
/**
 * The running xoot version.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "MetaOutput".
 */
export interface MetaOutput {
  version: string;
}
/**
 * Move a batch to another goal, or a subtask to another batch, with its
 * subtree. An item with children first returns a preview and a
 * confirm_token; send the same body plus the token to apply.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "MoveRequest".
 */
export interface MoveRequest {
  confirm_token?: string | null;
  expected_version: number;
  key: string;
  parent: string;
}
/**
 * A new display name, an extra alias, or both. The key prefix never
 * changes: keys and URLs are built from it.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ProjectRenameRequest".
 */
export interface ProjectRenameRequest {
  alias?: string | null;
  name?: string | null;
}
/**
 * Every registered project, by key prefix.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "ProjectsOutput".
 */
export interface ProjectsOutput {
  projects: ProjectInfo[];
}
/**
 * A preview returns the plan (the new key) and a confirm_token; an apply
 * returns the plan written, the item as it now stands, and the engine's
 * outcome. The old key keeps resolving to the item.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "PushOutput".
 */
export interface PushOutput {
  blocked?: BlockedEntry[];
  changed?: VersionEntry[];
  completed?: string[];
  confirm_token: string | null;
  item: AffectedItemEntry | null;
  phase: 'preview' | 'applied';
  plan: SubtreeOutput;
  project: string;
  reopened?: string[];
}
/**
 * Push a backlog item one level up. Always two-phase: the first call
 * returns the plan and a confirm_token; send the same body plus the token.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "PushRequest".
 */
export interface PushRequest {
  confirm_token?: string | null;
  key: string;
}
/**
 * An item and its depth below the query's roots.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "TreeEntry".
 */
export interface TreeEntry {
  depth: number;
  item: ItemSummary;
}
/**
 * Tree nodes in pre-order; truncated says the bounds hid items. blocked
 * lists every goal and batch of the project that open backlog holds open,
 * uncapped, so any node can show it.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "TreeView".
 */
export interface TreeView {
  blocked: BlockedEntry[];
  nodes: TreeEntry[];
  project: string;
  truncated: boolean;
}
/**
 * Every state of one kind with its category, in workflow order, and the
 * moves a user may make. transitions is null when any state may move to
 * any other; when the kind restricts them it maps every state name to the
 * states it may move to (possibly none). Keeping the current state is
 * always allowed and is not listed.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "WorkflowKindView".
 */
export interface WorkflowKindView {
  states: StateSpec[];
  transitions: {
    [k: string]: string[];
  } | null;
  transitions_restricted: boolean;
}
/**
 * The project's active workflow: every state of each item kind with its
 * category, as brief_get shows it, plus the allowed moves of a kind that
 * restricts them, so an editor offers only real states and real moves.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "WorkflowView".
 */
export interface WorkflowView {
  workflow: {
    [k: string]: WorkflowKindView;
  };
}
/**
 * A write error: the class name and safe message of ErrorOutput plus
 * details, always present. details is an empty object when there is
 * nothing to report, or structured facts such as a version conflict's
 * current version, changed fields and actors. A separate model, because
 * read errors keep their two-field body.
 *
 * This interface was referenced by `XootDashboardApi`'s JSON-Schema
 * via the `definition` "WriteErrorOutput".
 */
export interface WriteErrorOutput {
  details: {
    [k: string]: unknown;
  };
  error: string;
  message: string;
}
